- name: Deploy docker for usdttrc20 plugin
  import_role:
    name: chain-plugin
  vars:
    container_name: usdttrc20-plugin-{{ target_environment }}
    wallet_plugin_contract: '{{ usdttrc20_contract }}'
    wallet_plugin_env_coin_type: usdttrc20
    wallet_plugin_env_coin_api: '{{ usdttrc20_cluster_api }}'
    wallet_plugin_env_coin_token: ''
    wallet_plugin_env_coin_user: ''
    wallet_plugin_env_coin_pass: ''
