- name: Download bitcoin tarball
  get_url:
    url: '{{ download_url }}'
    dest: '{{ source_dir }}/{{ downloaded_package }}'
    checksum: sha256:2cca490c1f2842884a3c5b0606f179f9f937177da4eadd628e3f7fd7e25d26d0
  delegate_to: 127.0.0.1

- name: Create destination directory
  ansible.builtin.file:
    path: '{{ bitcoin_source_dir }}'
    state: directory
    recurse: yes
  delegate_to: 127.0.0.1

- name: Untar execution binary
  ansible.builtin.unarchive:
    src: '{{ source_dir }}/{{ downloaded_package }}'
    dest: '{{ bitcoin_source_dir }}'
  delegate_to: 127.0.0.1

- name: Copy execution binary
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: '{{ bitcoin_copy_dir }}/'
    dest: /usr
