- name: Check wallet info
  command: 'bitcoin-cli -rpcuser={{ bitcoin_rpcuser }} -rpcpassword={{ bitcoin_rpcpassword }} getwalletinfo'
  ignore_errors: true
  register: check_wallet

- name: Download bitcoin tarball
  get_url:
    url: '{{ download_url }}'
    dest: '{{ source_dir }}/{{ downloaded_package }}'
    checksum: sha256:2cca490c1f2842884a3c5b0606f179f9f937177da4eadd628e3f7fd7e25d26d0
  delegate_to: 127.0.0.1
  when: check_wallet.failed

- name: Create destination directory
  ansible.builtin.file:
    path: '{{ bitcoin_source_dir }}'
    state: directory
    recurse: yes
  delegate_to: 127.0.0.1
  when: check_wallet.failed

- name: Untar execution binary
  ansible.builtin.unarchive:
    src: '{{ source_dir }}/{{ downloaded_package }}'
    dest: '{{ bitcoin_source_dir }}'
  delegate_to: 127.0.0.1
  when: check_wallet.failed

- name: Create bitcoin user
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: bitcoin
    state: present
  when: check_wallet.failed

- name: Stop bitcoind daemon
  become: yes
  become_user: root
  become_method: sudo
  systemd:
    state: stopped
    name: bitcoind
  ignore_errors: true
  when: check_wallet.failed

- name: Copy execution binary
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: '{{ bitcoin_copy_dir }}/'
    dest: /usr
    mode: preserve
  when: check_wallet.failed

- name: Copy bitcoind service file
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: bitcoind.service.j2
    dest: /etc/systemd/system/bitcoind.service
    owner: root
    group: root
  when: check_wallet.failed

- name: Create chain directory
  become: yes
  become_user: root
  become_method: sudo
  ansible.builtin.file:
    path: '{{ chain_mountpoint }}/bitcoind'
    state: directory
    recurse: yes
    owner: bitcoin
    group: bitcoin
  when: check_wallet.failed

- name: Start bitcoind daemon
  become: yes
  become_user: root
  become_method: sudo
  systemd:
    state: started
    daemon_reload: yes
    name: bitcoind
  when: check_wallet.failed

- name: Create bitcoin wallet
  command: 'bitcoin-cli -rpcuser={{ bitcoin_rpcuser }} -rpcpassword={{ bitcoin_rpcpassword }} -named createwallet wallet_name={{ default_wallet }} descriptors=false load_on_startup=true avoid_reuse=true'
  ignore_errors: true
  when: check_wallet.failed

- name: Load bitcoin wallet
  command: 'bitcoin-cli -rpcuser={{ bitcoin_rpcuser }} -rpcpassword={{ bitcoin_rpcpassword }} loadwallet {{ default_wallet }}'
  ignore_errors: true
  when: check_wallet.failed

- name: Get wallet info
  command: 'bitcoin-cli -rpcuser={{ bitcoin_rpcuser }} -rpcpassword={{ bitcoin_rpcpassword }} getwalletinfo'
