- name: Download bitcoin tarball
  get_url:
    url: '{{ download_url }}'
    dest: '{{ source_dir }}/{{ downloaded_package }}'
    checksum: sha256:2cca490c1f2842884a3c5b0606f179f9f937177da4eadd628e3f7fd7e25d26d0
  delegate_to: 127.0.0.1

- name: Create destination directory
  ansible.builtin.file:
    path: '{{ bitcoin_source_dir }}'
    state: directory
    recurse: yes
  delegate_to: 127.0.0.1

- name: Untar execution binary
  ansible.builtin.unarchive:
    src: '{{ source_dir }}/{{ downloaded_package }}'
    dest: '{{ bitcoin_source_dir }}'
  delegate_to: 127.0.0.1

- name: Create bitcoin user
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: bitcoin
    state: present

- name: Stop bitcoind daemon
  become: yes
  become_user: root
  become_method: sudo
  systemd:
    state: stopped
    name: bitcoind
  ignore_errors: true

- name: Copy execution binary
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: '{{ bitcoin_copy_dir }}/'
    dest: /usr
    mode: preserve

- name: Copy bitcoind service file
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: bitcoind.service.j2
    dest: /etc/systemd/system/bitcoind.service
    owner: root
    group: root

- name: Create chain directory
  ansible.builtin.file:
    path: '{{ chain_mountpoint }}/bitcoind'
    state: directory
    recurse: yes

- name: Start bitcoind daemon
  become: yes
  become_user: root
  become_method: sudo
  systemd:
    state: started
    daemon_reload: yes
    name: bitcoind

- name: Create bitcoin wallet
  command: 'bitcoin-cli -rpcuser={{ bitcoin_rpcuser }} -rpcpassword={{ bitcoin_rpcpassword }} createwallet {{ default_wallet }}'
  ignore_errors: true

- name: Load bitcoin wallet
  command: 'bitcoin-cli -rpcuser={{ bitcoin_rpcuser }} -rpcpassword={{ bitcoin_rpcpassword }} loadwallet {{ default_wallet }}'
  ignore_errors: true

- name: Get wallet info
  command: 'bitcoin-cli -rpcuser={{ bitcoin_rpcuser }} -rpcpassword={{ bitcoin_rpcpassword }} getwalletinfo'
