- name: Precheck nvme mount point
  fail:
    msg: '{{ item }} mount point is not defined'
  when: item.mount is not defined
  with_items:
    - '{{ nvmes }}'

- name: Precheck nvme partition label
  fail:
    msg: '{{ item }} label is not defined'
  when: item.label is not defined
  with_items:
    - '{{ nvmes }}'

- name: Umount exist volumn
  become: yes
  become_user: root
  become_method: sudo
  ansible.posix.mount:
    path: '{{ item.mount }}'
    state: unmounted
  with_items:
    - '{{ nvmes }}'
  ignore_errors: true

- name: Create nvme partitions
  become: yes
  become_user: root
  become_method: sudo
  community.general.parted:
    device: '/dev/{{ item.name }}'
    number: 1
    state: present
    fs_type: xfs
  with_items:
    - '{{ nvmes }}'

- name: Create nvme filesystem
  become: yes
  become_user: root
  become_method: sudo
  community.general.filesystem:
    device: '/dev/{{ item.name }}p1'
    fstype: xfs
    state: present
    opts: '-L {{ item.label }}'
  with_items:
    - '{{ nvmes }}'

- name: Create mount point
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: '{{ item.mount }}'
    state: directory
    recurse: yes
  with_items:
    - '{{ nvmes }}'

- name: Mount nvme partitions
  become: yes
  become_user: root
  become_method: sudo
  ansible.posix.mount:
    path: '{{ item.mount }}'
    src: 'LABEL={{ item.label }}'
    fstype: xfs
    state: mounted
    opts: nofail
  with_items:
    - '{{ nvmes }}'
