- name: Deploy docker for usdcerc20 plugin
  import_role:
    name: chain-plugin
  vars:
    container_name: usdcerc20-plugin-{{ target_environment }}
    wallet_plugin_env_coin_type: usdcerc20
    wallet_plugin_env_coin_local_api: 'http://{{ ansible_default_ipv4.address }}:8545'
    wallet_plugin_env_coin_public_api: ''
    wallet_plugin_contract: ''
