- name: Deploy docker for binancecoin plugin
  import_role:
    name: chain-plugin
  vars:
    container_name: binancecoin-plugin-{{ target_environment }}
    wallet_plugin_contract: ''
    wallet_plugin_env_coin_type: binancecoin
    wallet_plugin_env_coin_local_api: ''
    wallet_plugin_env_coin_public_api: 'https://data-seed-prebsc-2-s3.binance.org:8545'
