- name: Deploy docker for bitcoin plugin
  import_role:
    name: chain-plugin
  vars:
    container_name: bitcoin-plugin-{{ target_environment }}
    wallet_plugin_contract: ''
    wallet_plugin_env_coin_type: bitcoin
    wallet_plugin_env_coin_local_api: '{{ ansible_default_ipv4.address }}:8332'
    wallet_plugin_env_coin_public_api: ''
    wallet_plugin_env_coin_token: ''
    wallet_plugin_env_coin_user: '{{ bitcoin_rpcuser }}'
    wallet_plugin_env_coin_pass: '{{ bitcoin_rpcpassword }}'
