- name: Print home directory
  debug: var=source_dir

- name: Print output directory
  debug: var=output_dir

- name: Print inventory directory
  debug: var=inventory_dir

- name: Create output directory
  ansible.builtin.file:
    path: '{{ output_dir }}'
    state: directory
    recurse: yes

- name: Create log directory
  ansible.builtin.file:
    path: '{{ log_dir }}'
    state: directory
    recurse: yes
